# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-12-13 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_file', models.FileField(upload_to='upload/')),
            ],
        ),
    ]
